[Environment] Build fingerprint: google/oriole/oriole:UpsideDownCake/MASTER/9381664:userdebug/dev-keys
[Environment] Patch level: 2023-01-05
[Environment] Local properties file "/data/local.prop" with contents:
None
+----------------------------------------Release Build Stacktrace----------------------------------------+
Command: /tradefed/adb shell HWASAN_OPTIONS=alloc_dealloc_mismatch=0:allocator_may_return_null=1:allow_user_segv_handler=1:check_malloc_usable_size=0:detect_container_overflow=0:detect_leaks=0:detect_odr_violation=0:detect_stack_use_after_return=1:fast_unwind_on_fatal=1:handle_abort=1:handle_segv=1:handle_sigbus=1:handle_sigfpe=1:handle_sigill=1:max_uar_stack_size_log=16:print_scariness=1:print_summary=1:print_suppressions=0:redzone=32:strict_memcmp=0:symbolize=0:use_sigaltstack=1 /data/fuzz/bot/builds/android-haiku_target-trusty_hwasan_trusty_keymaster_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/trusty_keymaster_fuzzer -rss_limit_mb=2560 -timeout=90 -runs=100 /data/fuzz/bot/clusterfuzz/bot/inputs/fuzzer-testcases/crash-01142aa360e756c62d533bf6b2bea27b8d1df7d9
Time ran: 5.093210697174072

+-- Logcat excerpt: Trusted App crash stacktrace --+
--------- trusty (0):
boot args 0x*** 0x*** 0x1000 0x0
gicc 0x***, gicd 0x***, gicr 0x***
mte is not available
initializing trusty (Project: slider-fuzz-test-debug, Build: davfu1@davfu1.c.googlers.com-7, Built: 02:38:50 Feb  7 2023)
sancov-rt: 227: sancov initialized with *** counters
ARM TRNG total time for 8 bytes: *** ns
sancov-rt: 227: sancov initialized with 1106 counters
_Bool sm_check_and_lock_api_version(uint32_t):127: min api version set: 2
sancov-rt: 227: sancov initialized with *** counters
sancov-rt: 227: sancov initialized with 3557 counters
sancov-rt: 227: sancov initialized with *** counters
sancov-rt: 227: sancov initialized with 1494 counters
sancov-rt: 227: sancov initialized with 460 counters
sancov-rt: 227: sancov initialized with 717 counters
sancov-rt: 227: sancov initialized with 777 counters
sancov-rt: 227: sancov initialized with *** counters
sancov-rt: 227: sancov initialized with 702 counters
[GF_TA][E][gf_secure_object][gf_so_load_persistent_object] so(gf_fake_trace_info_0.so) not exist
[GF_TA][E][gf_secure_object][gf_so_load_persistent_object] exit. err=GF_ERROR_OPEN_SECURE_OBJECT_FAILED, errno=1035
[GF_TA][E][gf_tee_storage][gf_tee_open_object] exit. err=GF_ERROR_OPEN_SECURE_OBJECT_FAILED, errno=1035
[GF_TA][E][gf_secure_object][gf_so_load_persistent_object] so(gf_fake_trace_info_0.so_bak) not exist
[GF_TA][E][gf_secure_object][gf_so_load_persistent_object] exit. err=GF_ERROR_OPEN_SECURE_OBJECT_FAILED, errno=1035
[GF_TA][E][gf_local_store_utils][gf_store_load_buffer] load (gf_fake_trace_info_0.so_bak) failed
[GF_TA][E][gf_local_store_utils][gf_store_load_buffer] exit. err=GF_ERROR_OPEN_SECURE_OBJECT_FAILED, errno=1035
[GF_TA][E][gf_local_store_file_system][gf_load_data_from_so] read data (gf_fake_trace_info_0.so) failed
[GF_TA][E][gf_local_store_file_system][gf_load_data_from_so] exit. err=GF_ERROR_OPEN_SECURE_OBJECT_FAILED, errno=1035
[GF_TA][E][gf_local_store_fs_internal][gf_file_store_get] exit. err=GF_ERROR_OPEN_SECURE_OBJECT_FAILED, errno=1035
[GF_TA][E][gf_hw][hw_get_data] exit. err=GF_ERROR_OPEN_SECURE_OBJECT_FAILED, errno=1035
[GF_TA][E][gf_algo_adapter][gf_adt_load_fake_trace_log] exit. err=GF_ERROR_OPEN_SECURE_OBJECT_FAILED, errno=1035
ROTLAYER2: 120: WTPI_LoadRootOfTrust: error opening keybox on TP. Attempting TDP.
ROTLAYER2: 125: WTPI_LoadRootOfTrust: error opening keybox: -2
trusty_keymaster (err): trusty/user/app/keymaster/trusty_keymaster.cpp, Line 47: HAL sent invalid message version 513, crashing
void trusty_app_exit(int):1670: trusty_app_2_5f902ace-5e5c-4cd8: exited with exit code 127LAST TESTED STACKTRACE ON REVISION 8929774 (9352 LINES)
[Environment] Build fingerprint: google/raven/raven:UpsideDownCake/MASTER/9321118:userdebug/dev-keys
[Environment] Patch level: 2023-01-05
[Environment] Local properties file "/data/local.prop" with contents:
None
trusty_keymaster (err): trusty/user/app/keymaster/ipc/keymaster_ipc.cpp, Line 764: error handling message (-7)
trusty_keymaster (err): trusty/user/app/keymaster/trusty_keymaster.cpp, Line 47: HAL sent invalid message version ***, crashing
void trusty_app_exit(int):1670: trusty_app_2_5f902ace-5e5c-4cd8: exited with exit code 127
Backtrace for thread: trusty_app_2_5f902ace-5e5c-4cd8
(app: keymaster)
kSP+0x0a10: 0xffff000000043210 in sys_brk ld-temp.o:?
kSP+0x0b30: 0xffff000000283ccc in $x.0 arm64/syscall.S:57
kSP+0x0c10: 0x0000000000087710 in lk.elf
uSP+0x7d80: 0x0000000000035290 in sha512_block sha512-armv8.S:1317
uSP+0x7a40: 0x00000000001392a8 in sha512_block sha512-armv8.S:809
Project: cloudripper-fuzz-test-debug, Build: davfu1@davfu1.c.googlers.com-6, Built: 20:18:00 Feb  6 2023

INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1080409365
INFO: Loaded 9 modules   (28613 inline 8-bit counters): 17389 [0x788996cd50, 0x788997113d), 1480 [0x788da79690, 0x788da79c58), 18 [0x788dd5f2e0, 0x788dd5f2f2), 7169 [0x788fbcddf8, 0x788fbcf9f9), 155 [0x78914623b8, 0x7891462453), 1627 [0x788fb27a68, 0x788fb280c3), 388 [0x788ddf87d8, 0x788ddf895c), 262 [0x7889d2f048, 0x7889d2f14e), 125 [0x62ecdea030, 0x62ecdea0ad),
INFO: Loaded 9 PC tables (28613 PCs): 17389 [0x7889971140,0x78899b5010), 1480 [0x788da79c58,0x788da7f8d8), 18 [0x788dd5f2f8,0x788dd5f418), 7169 [0x788fbcfa00,0x788fbeba10), 155 [0x7891462458,0x7891462e08), 1627 [0x788fb280c8,0x788fb2e678), 388 [0x788ddf8960,0x788ddfa1a0), 262 [0x7889d2f150,0x7889d301b0), 125 [0x62ecdea0b0,0x62ecdea880),
INFO: 65536 Extra Counters
/data/fuzz/bot/builds/android-haiku_target-trusty_hwasan_trusty_keymaster_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/trusty_keymaster_fuzzer: Running 1 inputs 100 time(s) each.
Running: /data/fuzz/bot/clusterfuzz/bot/inputs/fuzzer-testcases/crash-01142aa360e756c62d533bf6b2bea27b8d1df7d9
failed to open TIPC device: : Connection timed out
==9154== ERROR: libFuzzer: fuzz target exited
#0 0x788da9bc2c in __sanitizer_print_stack_trace out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:589:3
#1 0x62ecde5eec in fuzzer::PrintStackTrace() out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
#2 0x62ecdc4364 in fuzzer::Fuzzer::ExitCallback() out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:250:3
#3 0x7889e96454 in __cxa_finalize bionic/libc/bionic/atexit.cpp:261:5
#4 0x7889e831ac in exit bionic/libc/bionic/exit.cpp:49:3
#5 0x7889ce4ebc in android::trusty::fuzz::Abort() system/core/trusty/fuzz/utils.cpp:136:5
#6 0x62ecdb2614 in LLVMFuzzerTestOneInput system/core/trusty/fuzz/tipc_fuzzer.cpp:92:9
#7 0x62ecdc57a8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
#8 0x62ecdba3f4 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
#9 0x62ecdbf614 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
#10 0x62ecde64b0 in main out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
#11 0x7889df76c4 in __libc_init bionic/libc/bionic/libc_init_dynamic.cpp:157:8
#12 0x62ecdb1050 in _start_main bionic/libc/arch-common/bionic/crtbegin.c:45:3
SUMMARY: libFuzzer: fuzz target exited
